[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor = "#004741"
backgroundColor = "#F0EDE4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1C2E2C"
font = "sans serif"
